spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

camunda.bpm.admin-user:
  id: user
  password: 1234
camunda:
  bpm:
    enabled: true
    process-engine-name: default
    admin-user:
      id: user
      password: 1234
    generic-properties:
      properties:
        historyTimeToLive: 5



#spring:
#  datasource:
#    url: jdbc:h2:file:./database
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#
#camunda:
#  bpm:
#    enabled: true
#    process-engine-name: default
#    admin-user:
#      id: user
#      password: 1234
#    generic-properties:
#      properties:
#        historyTimeToLive: 5
#    database:
#      type: h2
#      schema-update: true